# Generated by Django 3.0.2 on 2020-01-07 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('health', models.IntegerField(default=0)),
                ('object_type', models.CharField(default=None, max_length=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, unique=True)),
                ('vk_id', models.IntegerField(unique=True)),
                ('token', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='DynamicObject',
            fields=[
                ('gameobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.GameObject')),
            ],
            bases=('game.gameobject',),
        ),
        migrations.CreateModel(
            name='StaticObject',
            fields=[
                ('gameobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.GameObject')),
            ],
            bases=('game.gameobject',),
        ),
        migrations.CreateModel(
            name='MapObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('game_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='on_map', to='game.GameObject')),
            ],
        ),
    ]
