# Generated by Django 3.0.2 on 2020-01-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='token',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
    ]
