# Generated by Django 3.0.2 on 2020-01-08 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gameobject_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameobject',
            name='owner',
        ),
        migrations.AddField(
            model_name='mapobject',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_objects', to='game.Person'),
        ),
    ]
