# Generated by Django 3.0.2 on 2020-01-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_person_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamicobject',
            name='object_type',
        ),
        migrations.RemoveField(
            model_name='staticobject',
            name='object_type',
        ),
        migrations.AddField(
            model_name='gameobject',
            name='object_type',
            field=models.CharField(default=None, max_length=7, null=True),
        ),
    ]
