# Generated by Django 3.0.2 on 2020-01-09 16:49

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('game', '0003_auto_20200108_1656'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Player',
        ),
    ]
