# Generated by Django 3.0.2 on 2020-01-10 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
