# Generated by Django 3.0.2 on 2020-01-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20200110_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='vk_id',
        ),
        migrations.AddField(
            model_name='player',
            name='metadata',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='user_id',
            field=models.CharField(default=None, max_length=32, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gameobject',
            name='health',
            field=models.IntegerField(default=10),
        ),
    ]
