# Generated by Django 3.0.2 on 2020-01-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20200122_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameobject',
            name='uuid',
            field=models.UUIDField(default=None, null=True),
        ),
    ]
